#!/bin/bash
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:species -lang:species
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikibooks -lang:es
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikibooks -lang:eu
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikibooks -lang:gl
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikinews -lang:es
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikipedia -lang:an
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikipedia -lang:ang
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikipedia -lang:es
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikipedia -lang:eu
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikipedia -lang:sco
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikipedia -lang:tcy
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikiquote -lang:en
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikiquote -lang:es
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikiquote -lang:eu
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikiquote -lang:gl
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikisource -lang:es
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wikivoyage -lang:es
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wiktionary -lang:an
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wiktionary -lang:ast
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wiktionary -lang:es
$HOME/pwbvenv/bin/python3 $HOME/pywikibot-core/pwb.py archivebot User:MABot/config -family:wiktionary -lang:gl
